### ISSUE TITLE
Breaks if lazy loaded module has anything else than the react component make function

### ISSUE THREAD

**Issue by TomiS** [jchavarri/reason-react-lazy-loading#1]
Hi. This is a very interesting example project. I tried to apply it to my real life application and noticed that if the component that is being lazy loaded has anything else than `let make = ...` and `let default = make` like in your example file `PdfPreview.re`, it will break. It breaks if I add `Styles` module into the same file. It breaks if I just add another function e.g. `let foo = () => "hey";`

What do you think, is there a way to make this a little bit less brittle? I would guess almost all react components have something else than the actual component in the file.
 
Btw, the nasty part is that it still builds nicely in Reason and only the javascript is broken.

**Comment by jchavarri** [comment]
Hey @TomiS thanks for bringing this up.

The approach being used with `include` was very dangerous as you noticed. There is a lot of "type magic" going on as we lie to the compiler with the line `[@bs.val] external component: (module T) = "undefined";`, which creates a value out of the blue that has the same type as the original component, but it really is `undefined`.

I tried a different, more manual, and hopefully safer approach in #2. The idea is to avoid exposing all declarations from the original component, but just expose `makeProps` (which luckily gets inlined in the lazy component by BuckleScript, which avoids having a `require` in resulting code) and the lazy `make`. All other declarations are not be exposed.

Please let me know if this covers the use case you mentioned :)

**Comment by TomiS** [comment]
@jchavarri I think it's better than before. However I didn't get it working. It gives `uncaught null` js error in my app now. My current theory is that it relates to introducing context in main component and then trying to use the context inside lazy loaded component. It might be something completely different too, so I'm going to test this theory asap (unless you can straight up say that it's either true or impossible).

**Comment by TomiS** [comment]
@jchavarri Actually, I'll take that back. I'm afraid it does not work at all. I tried running your branch but it gives the same `Uncaught null` error even if I don't modify the code in any way. This happens in dev mode at least I didn't try prod build.

**Comment by jchavarri** [comment]
> My current theory is that it relates to introducing context in main component and then trying to use the context inside lazy loaded component.

Would it be possible for you to paste a snippet in this issue that shows how the lazy component is being declared in your case? Note that with the newer approach in #2:
- only `make` and `makeProps` have to be declared in lazy component
- no `include` should be used in lazy component

The `Uncaught null` errors sound intriguing. If there was an issue with declarations not being available in the runtime code, it would be something similar to `can't get property bla of undefined`. But there are no `null` values being set in this approach, as far as I can tell. 🤔

**Comment by TomiS** [comment]
I mean, I cannot even run this test repository. I get the error immediately after clicking the "Generate PDF" button in the form. So it works for you, I guess? That's weird...
I get this error: https://imgur.com/a/DoM8TUh

**Comment by jchavarri** [comment]
Oh, I see. It seems I added some changes in the `import` bindings, but I tested a stale version of js code. It should be fixed in https://github.com/jchavarri/reason-react-lazy-loading/pull/2/commits/5c6c692ed604b35f450e7496770499747670ef6e. :)

**Comment by TomiS** [comment]
Ok, confirming that now it works also for a random use case like mine :)

If someone else looks at this, it's worth noting that the line `let default = make` is very much required in the component that is being lazy loaded. Otherwise there will be no default export for that component in javascript and the implementation crashes because of that.

**Comment by jchavarri** [comment]
Awesome! Thanks for reporting back.

> If someone else looks at this, it's worth noting that the line `let default = make` is very much required in the component that is being lazy loaded.

Great point. I think there might be a way to formalize this requirement by using a functor. I will noodle a bit more after merging #2 to see if it is possible without complicating things further.
